# Generated by Django 4.0.4 on 2022-05-10 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='cover_picture',
            field=models.URLField(blank=True, help_text='cover picture will be displayed in your profile page', null=True, verbose_name='add cover picture'),
        ),
    ]
