# Generated by Django 4.0.4 on 2022-04-25 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_developer_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='disallow_login',
            field=models.DateTimeField(blank=True, default=None, help_text='account suspended for some time due to repeated failed login', null=True, verbose_name='account frozen temporarily'),
        ),
    ]
