# Generated by Django 4.0.4 on 2022-04-28 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_account_disallow_login'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='account',
            name='username_idx',
        ),
        migrations.RemoveIndex(
            model_name='account',
            name='email_idx',
        ),
        migrations.RemoveIndex(
            model_name='account',
            name='first_name_idx',
        ),
        migrations.RemoveIndex(
            model_name='account',
            name='last_name_idx',
        ),
        migrations.RemoveIndex(
            model_name='account',
            name='preferred_name_idx',
        ),
        migrations.RemoveIndex(
            model_name='account',
            name='gender_idx',
        ),
        migrations.RemoveIndex(
            model_name='account',
            name='phone_number_idx',
        ),
        migrations.RemoveIndex(
            model_name='account',
            name='full_name_idx',
        ),
        migrations.RemoveIndex(
            model_name='account',
            name='first_name_gender_idx',
        ),
        migrations.RemoveIndex(
            model_name='account',
            name='last_name_gender_idx',
        ),
        migrations.RemoveIndex(
            model_name='account',
            name='preferred_name_gender_idx',
        ),
        migrations.RemoveIndex(
            model_name='account',
            name='full_name_gender_idx',
        ),
        migrations.AlterField(
            model_name='account',
            name='is_active',
            field=models.BooleanField(default=False, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active'),
        ),
        migrations.AddIndex(
            model_name='account',
            index=models.Index(fields=['username'], name='accounts_ac_usernam_862e8e_idx'),
        ),
        migrations.AddIndex(
            model_name='account',
            index=models.Index(fields=['email'], name='accounts_ac_email_b00920_idx'),
        ),
        migrations.AddIndex(
            model_name='account',
            index=models.Index(fields=['first_name'], name='accounts_ac_first_n_7983cf_idx'),
        ),
        migrations.AddIndex(
            model_name='account',
            index=models.Index(fields=['last_name'], name='accounts_ac_last_na_12b48c_idx'),
        ),
        migrations.AddIndex(
            model_name='account',
            index=models.Index(fields=['preferred_name'], name='accounts_ac_preferr_cc3056_idx'),
        ),
        migrations.AddIndex(
            model_name='account',
            index=models.Index(fields=['gender'], name='accounts_ac_gender_76fa0d_idx'),
        ),
        migrations.AddIndex(
            model_name='account',
            index=models.Index(fields=['phone_number'], name='accounts_ac_phone_n_019c95_idx'),
        ),
        migrations.AddIndex(
            model_name='account',
            index=models.Index(fields=['first_name', 'last_name'], name='accounts_ac_first_n_fae401_idx'),
        ),
        migrations.AddIndex(
            model_name='account',
            index=models.Index(fields=['first_name', 'gender'], name='accounts_ac_first_n_32da31_idx'),
        ),
        migrations.AddIndex(
            model_name='account',
            index=models.Index(fields=['last_name', 'gender'], name='accounts_ac_last_na_8bd2eb_idx'),
        ),
        migrations.AddIndex(
            model_name='account',
            index=models.Index(fields=['preferred_name', 'gender'], name='accounts_ac_preferr_e4827b_idx'),
        ),
        migrations.AddIndex(
            model_name='account',
            index=models.Index(fields=['first_name', 'last_name', 'gender'], name='accounts_ac_first_n_a9b081_idx'),
        ),
        migrations.AddIndex(
            model_name='developer',
            index=models.Index(fields=['access_key'], name='accounts_de_access__37387e_idx'),
        ),
        migrations.AddIndex(
            model_name='developer',
            index=models.Index(fields=['developer_secret_key'], name='accounts_de_develop_535bc1_idx'),
        ),
    ]
