# Generated by Django 4.0.4 on 2022-05-28 09:03

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('city_number', models.IntegerField(primary_key=True, serialize=False)),
                ('city_name', models.CharField(max_length=50, verbose_name='city')),
                ('label', models.CharField(blank=True, max_length=50, verbose_name='label for city')),
                ('boundary', django.contrib.gis.db.models.fields.PolygonField(srid=4326)),
            ],
        ),
        migrations.CreateModel(
            name='County',
            fields=[
                ('county_number', models.IntegerField(primary_key=True, serialize=False)),
                ('county_name', models.CharField(max_length=50, verbose_name='county')),
                ('label', models.CharField(blank=True, max_length=50, verbose_name='label for county')),
                ('boundary', django.contrib.gis.db.models.fields.PolygonField(srid=4326)),
            ],
        ),
        migrations.CreateModel(
            name='PostalCode',
            fields=[
                ('postal_code', models.IntegerField(primary_key=True, serialize=False)),
                ('postal_location', models.CharField(max_length=50, verbose_name='postal location')),
                ('label', models.CharField(blank=True, max_length=50, verbose_name='label for postal code')),
                ('boundary', django.contrib.gis.db.models.fields.PolygonField(srid=4326)),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='locations.city')),
            ],
        ),
        migrations.AddField(
            model_name='city',
            name='county',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='locations.county'),
        ),
    ]
